# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_transcript_transcriptline'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='transcript',
            field=models.ForeignKey(blank=True, help_text='If you do not add a transcript, one will not be displayed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Transcript'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(help_text='Make sure these are square. Pay special attention to file size when creating these, since they are displayed frequently.', upload_to=b'', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(verbose_name='Date Recorded'),
        ),
    ]
