# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20170601_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-recorded_date', 'slug'], 'verbose_name_plural': 'stories'},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='date',
            new_name='recorded_date',
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(help_text='Appears at the top of stories and on index pages. Supports markdown.'),
        ),
        migrations.AlterField(
            model_name='story',
            name='transcript',
            field=models.ForeignKey(blank=True, help_text='If you do not add a transcript, one will not be displayed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='stories.Transcript'),
        ),
    ]
