# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20170908_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='air_date',
            field=models.DateField(null=True, verbose_name='Date First Aired'),
        ),
    ]
